apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: konnek-receiver
spec:
  template:
    metadata: 
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: konnek/knative-receiver
