apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: konnek-trigger-aws-sqs
spec:
  broker: default
  filter:
    attributes:
      type: com.amazon.sqs
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: konnek-consumer